//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public System.Guid ObjId { get; set; }
        public string Term { get; set; }
        public string Subject { get; set; }
        public string Link { get; set; }
        public Nullable<System.Guid> SubjectID { get; set; }
        public string PaperNo { get; set; }
        public string Year { get; set; }
        public string Type { get; set; }
    }
}
