//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolSub
    {
        public System.Guid ObjId { get; set; }
        public string Grade { get; set; }
        public string SubjectName { get; set; }
        public string Topics { get; set; }
        public string Link { get; set; }
        public string Term { get; set; }
        public string Weeks { get; set; }
        public string ExamPaperLink { get; set; }
    }
}
